### PR TITLE
Increase postgres startup timeout

### PR DESCRIPTION
**Pull request by weissjeffm**

### CODE REVIEW

**Comment by weissjeffm** [comment]
Hopefully the solution to https://github.com/monetas/gotary/issues/404

**Comment by toxeus** [comment]
@weissjeffm didn't you try locally?

**Comment by weissjeffm** [comment]
@toxeus yes I did:

```
[jweiss@localhost golang-base]$ docker run --rm --interactive=true --tty=true db0e19472ce0 sh -c 'sudo sh /opt/run_services.sh' 
Starting supervisor: supervisord.
/var/run/postgresql:5432 - accepting connections
[jweiss@localhost golang-base]$ 
```

:confused:

**Comment by toxeus** [comment]
I think with that command it's expected to leave the container. You should try to reproduce the other command.

**Comment by weissjeffm** [comment]
Ok, postgres still fails to start even after increasing the timeout. So this is not a timing related issue.

Closing

**Pull request closed without merging**
