### PR TITLE
Migrate to gradle

### PR DESCRIPTION
**Pull request by weissjeffm**

### CODE REVIEW

**Comment by vds** [comment]
:+1:

**Comment by mhamrle** [comment]
:+1:

**Comment by OttoAllmendinger** [comment]
just a sec, I discovered some things that are missing

**Comment by OttoAllmendinger** [comment]
can you please add these lines on top after `apply plugin: 'java'`

```groovy
// dependency management
apply plugin: 'maven'

group = "net.monetas.gruenhof"
version = "0.1.0-SNAPSHOT"

// make this usable in android
tasks.withType(JavaCompile) {
    sourceCompatibility = "1.7"
    targetCompatibility = "1.7"
}
```

**Comment by mhamrle** [comment]
I though about the same but it should be in gotary repo?

**Comment by OttoAllmendinger** [comment]
@mhamrle long-term, `jarlie/` will go to a different github repo. I still need these lines so that `gradle install` works and I can use `jarlie` as a dependency in the android app.

**Comment by OttoAllmendinger** [comment]
Oops, this is the `monetas/dockerfiles`. 

In any case, we should just use the same `build.gradle` here and in `monetas/gotary`.

**Comment by weissjeffm** [comment]
ok will fix in both places. I knew I was dropping that info but didn't know if it was needed (since I think maven requires it)

**Pull request merged**
