### PR TITLE
Add java-base image for jarlie

### PR DESCRIPTION
**Pull request by OttoAllmendinger**
Jarlie dependencies are stored in `pom.xml`

### CODE REVIEW

**Comment by OttoAllmendinger** [comment]
waiting for `docker build` to finish...

**Comment by OttoAllmendinger** [comment]
Looks good

```
Step 0 : FROM ubuntu:14.04
 ---> 07f8e8c5e660
Step 1 : MAINTAINER Filip Gospodinov "filip@monetas.net"
 ---> Using cache
 ---> 6e2ccf99d5b3
Step 2 : ADD pom.xml ./
 ---> Using cache
 ---> e7f5d8f4b513
Step 3 : RUN apt-get update &&     apt-get install -y --no-install-recommends git maven ope
njdk-7-jdk &&     apt-get autoremove
 ---> Using cache
 ---> aa1c28537f4d
Step 4 : RUN mvn install
 ---> Using cache
 ---> f61993f30bc4
Step 5 : CMD bash
 ---> Running in 101112e7d927
 ---> 3fe1c6ef8954
Removing intermediate container 101112e7d927
Successfully built 3fe1c6ef8954
```

**Comment by toxeus** [comment]
:+1:

**Comment by benma** [comment]
:ok: :accept:

**Pull request merged**
