### PR TITLE
Change the base image to ubuntu:14.10

### PR DESCRIPTION
**Pull request by gsalgado**

### CODE REVIEW

**Comment by mhamrle** [comment]
Could you write more information why is it needed? I though that we are using ubuntu 14.04 because it will be used also in production because 14.04 is latest LTS.

**Comment by gsalgado** [comment]
For development, since we're sharing $HOME between host/container, it'd be a good idea if they were both on the same version. For instance, I have compiled vim extensions that don't work on the container as they were built on 14.10. I know not everyone is using Ubuntu as host, but for those who are it'd be good.

For production, I'm not sure it makes sense to target 14.04 as that's already a year old and we're nowhere near going into production. If that has been agreed upon, though, we should probably specify that in the FROM line.

**Comment by mhamrle** [comment]
It make sense to stay with production image on 14.04 LTS because it has support until 2019 but ubuntu 14.10 has support only for next 4 months. So official image is based on LTS and CI tests should run on official image.

I understand the problem with the development. I think you can rebuild the image locally with changed ubuntu version.

**Comment by gsalgado** [comment]
When developing we should use the same OS version that we're going to deploy on. If it's been decided that we'll stick with 14.04, then so be it

**Pull request closed without merging**
