### PR TITLE
Tweak postgres' config to improve performance

### PR DESCRIPTION
**Pull request by gsalgado**

### CODE REVIEW

**Comment by vds** [comment]
:+1:

**Comment by benma** [comment]
From the docs: 

> Durability is a database feature that guarantees the recording of committed transactions even if the server crashes or loses power. However, durability adds significant database overhead, so if your site does not require such a guarantee, PostgreSQL can be configured to run much faster. 

Could you please write something about the reasoning? Is it preferable to lose transactions to gain speed? How much speed gain are we talking? How many transactions can be lost if the server crashes (only the last one, or the last N minutes worth?). I don't know how often postgres flushes to disk if you disable flushing on every commit.

**Comment by gsalgado** [comment]
This is the postgres config for running tests. We don't care about
losing data if there's a power outage or the server crashes

**Comment by benma** [comment]
Right :smile_cat: Please add a comment that this is meant for the testing environment only. If we ever create a production dockerfile, the starting point might be the test dockerfile, so better be safe here. Not that it is accidentally forgotten and left in there.

**Comment by benma** [comment]
:+1: after that comment.

**Pull request merged**
