### PR TITLE
Do not use password auth on postgres

### PR DESCRIPTION
**Pull request by gsalgado**

### CODE REVIEW

**Comment by gsalgado** [comment]
@benma approved it in person

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
@monetas-ci test this please

**Comment by toxeus** [comment]
test this please

**Comment by weissjeffm** [comment]
test this please

**Comment by weissjeffm** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Comment by mhamrle** [comment]
:+1: if you fix build by incrementing version

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Pull request merged**
