### PR TITLE
add Libsodium into java-base

### PR DESCRIPTION
**Pull request by mhamrle**
needed by kalium java library

### CODE REVIEW

**Comment by OttoAllmendinger** [comment]
:+1:

**Comment by OttoAllmendinger** [comment]
also removes wrong `Base58Codec` library

**Comment by OttoAllmendinger** [comment]
I think you also need to bump the version to `3` -- paging @toxeus

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
test this please

**Comment by toxeus** [comment]
:+1:

**Pull request merged**
